version: '3.2'
volumes:
  postgres:

services:
  postgres:
    container_name: postgres
    image: postgres:11.5-alpine
    volumes:
      - ./docker/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./docker/insert_data.sql:/docker-entrypoint-initdb.d/insert_data.sql
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=Welcome
      - POSTGRES_USER=postgres
      - POSTGRES_DB=conference_app

#APP**
  web:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/conference_app
      DB_USER: postgres
      DB_PASS: Welcome
    expose:
      - '8080'
    depends_on:
      - postgres
    ports:
      - '8080:8080'

